services:
  test.db:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - 2433:1433
    volumes:
      - db:/var/opt/mssql
volumes:
  db:
    name: db